---
- name: Installing dependencies
  hosts: all
  become: yes
  tasks:
    # - name: Updating in Visudo
    #   lineinfile:
    #     path: visudo
    #     line: ansibleslave ALL=(ALL) NOPASSWD:ALL
    #     state: present 
    - name: Updating yum
      yum: name=* state=latest  
    - name: Getting node dependencies
      shell: curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -
    - name: Installing nodejs
      yum:
        name: nodejs
        state: present
    - name: Installing nginx
      shell: amazon-linux-extras install nginx1 -y
    - name: Installing Git
      yum:
        name: git
        state: present
    - name: Creating build folder
      file:
        path: /var/www/jenkins-react-app
        state: directory
    # - name: Creating build folder
    #   file:
    #     path: /home/ansibleslave/jenkins-react-app
    #     state: directory
    - name: Checkout Git Repo
      git: 
        repo: 'https://github.com/oshanfernando/jenkins-react-app.git/'
        dest: /home/ansibleslave/jenkins-react-app
    - name: Install dependencies
      shell: npm install
    - name: build
      shell: |
             cd /home/ansibleslave/jenkins-react-app 
             npm run build 
    - name: Deploy
      shell: |
             rm -rf /var/www/jenkins-react-app
             cp -r /home/ansibleslave/jekins-react-app/build/ /var/www/jenkins-react-app/
    - name: Update nginx configuration
      blockinfile: 
        path: /etc/nginx/nginx.conf
        block: |
               server {
                  listen 3000;
                  server_name 18.216.4.10; #public ip of ec2
                  root /var/www/jenkins-react-app; #root built path
                  index index.html; #starting file of project
                  
                  access_log /var/log/nginx/jenkins-react-app.log;
                  error_log /var/log/nginx/jenkins-react-app.error.log;
                  location / {
                    try_files $uri /index.html =404;
                  }
                }
    - name: Start server
      shell: service nginx start 



