---
- name: Installing dependencies
  hosts: all
  become: yes
  tasks:
    # - name: Updating in Visudo
    #   lineinfile:
    #     path: visudo
    #     line: ansibleslave ALL=(ALL) NOPASSWD:ALL
    #     state: present 
    - name: Updating yum
      yum: name=* state=latest  
    - name: Getting node dependencies
      shell: curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -
    - name: Installing nodejs
      yum:
        name: nodejs
        state: present
    - name: Installing nginx
      yum: 
        name: nginx
        state: latest
    - name: Creating build folder
      file:
        path: /var/www/jenkins-react-app
        state: directory
    